on:
  push:
    paths:
      - .github/workflows/publish.yml
      - .github/workflows/test_publish.yml
  pull_request:
    paths:
      - .github/workflows/publish.yml
      - .github/workflows/test_publish.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release_default:
    uses: ./.github/workflows/publish.yml
    with:
      test_extras: test
      test_command: pytest --pyargs test_package
      timeout-minutes: 30
  release:
    uses: ./.github/workflows/publish.yml
    with:
      test_extras: test
      test_command: pytest --pyargs test_package
      targets: |
        - linux
        - cp38-macosx_x86_64
        - cp39-macosx_arm64
        - cp3?-win_amd64
        - cp39-manylinux_aarch64
      timeout-minutes: 30
  release_sdist_only:
    uses: ./.github/workflows/publish.yml
    with:
      test_extras: test
      test_command: pytest --pyargs test_package
      targets: ''
