on:
  push:
    paths:
      - .github/workflows/publish_pure_python.yml
      - .github/workflows/test_publish_pure_python.yml
  pull_request:
    paths:
      - .github/workflows/publish_pure_python.yml
      - .github/workflows/test_publish_pure_python.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/publish_pure_python.yml
    with:
      test_extras: test
      test_command: pytest --pyargs test_package
      timeout-minutes: 5

  setenv:
    uses: ./.github/workflows/publish_pure_python.yml
    with:
      test_command: python -c "import os; assert os.getenv('CUSTOM_VAR') == 'custom value'"
      env: |
        CUSTOM_VAR: custom value
